name: 'Advanced Installer Tool'
description: 'Deploys Advanced Installer tool and builds an AIP project.'
author: 'Caphyon'
inputs:
  advinst-version:
    description: 'Advanced Installer version to deploy'
    required: false
  advinst-license:
    description: 'Advanced Installer version to acquire. If no version is specified the latest will be used. For a list of available versions please see http://www.advancedinstaller.com/version-history.html'
    required: false
  advinst-enable-automation:
    description: 'Use advanced installer from COM interfaces and PowerShell commands. This capability needs Advanced Installer 16.1 or higher.'
    required: false
    default: 'false'
  aip-path:
    description: 'Path to the AIP project to build'
    required: false
  aip-build-name:
    description: 'Name of the AIP project build configuration'
    required: false
  aip-package-name:
    description: 'Path to the build output package name'
    required: false
  aip-output-dir:
    description: 'Path to the build output directory'
    required: false
  aip-commands:
    description: 'Commands to execute in the AIP project'
    required: false

runs:
  using: 'node16'
  main: 'main\index.js'
  post: 'post\index.js'
